### ISSUE TITLE
`decl` attribute of static variables in C-files not unique between different files

### ISSUE THREAD

**Issue by rodinaarssen** [usethesource/clair#18]
As pointed out by @DavyLandman, the `decl` of static C-variables is not unique, as they are inherently unqualified. Given that these variables are local to a file anyway, this may or may not be a problem. Furthermore, ClaiR is currently built to parse C++, not C.

**Comment by DavyLandman** [comment]
I'm a bit rusty, but isn't the problem if you analyse multiple files in the same run? that if they both have a `static int A` that those names are not stable?

I agree that it's made for C, but even C++ allows static functions inside a `.cpp` file. you don't have access to the fields of the class, but utility functions often don't need to.

**Comment by rodinaarssen** [comment]
This will indeed only become an issue if you parse multiple files containing the same static variable. The `decl`s will then coincide.

Well, at the very least, we could explore this a little further then.

**Comment by jurgenvinju** [comment]
Declarations bound by the translationUnit are being prefixed with the translation unit's name (since a while):

For example:
```
 |cpp+parameter:///src/test/phonebook.cpp/strncpy(char.*,const.char.*,int)/len|
```  

That should solve this issue. Here phonebook.cpp has its own copy of strncpy (not #included)
