### ISSUE TITLE
declarations missing from containment relation

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/clair#41]
```
public:
    Cell(int);

    void addPlayerToCell(Player &player);

    virtual std::pair<int, int> getPositionCell() = 0;

    virtual void movePosition(int &position) = 0;

    virtual const std::string getTypeOfCell() = 0;

    void deletePlayerFromCell(Player &player);

    friend std::ostream &
    operator<<(std::ostream &output, Cell &cell);
};
```

For this example from snakes_and_ladders  `operator<<` are missing from the containment relation

**Comment by rodinaarssen** [comment]
Is that `operator<<` truly contained? What does CDT say?

**Comment by jurgenvinju** [comment]
Nope. my bad. The operator<< is a global function in the translationUnit. Syntactically encapsulated by the class, but static semantics of C++ says that the function is global anyway.
