### ISSUE TITLE
Declarations of class in M3.declarations lead to all usages as well. 

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/clair#48]
When we experiment with C++ code in clair we figured out that `m.declarations[classLoc]` led to more than just the declaration of the class. It also contains field definitions of the type of that class in other classes and friend declarations, etc. This is breaking analysis accuracy.

**Comment by jurgenvinju** [comment]
the actual declarations of those fields are _not_ present in m3.declarations. So it seems that the declarations of the fields are replaced by the type of the thing they are declaring.

**Comment by rodinaarssen** [comment]
Having an example here would be very helpful, as I can only guess what you're looking at now.

What I can comment is that this table is filled using a couple of deep matches in `lang::cpp::M3.rsc`, lines 53-57. It's likely that this is not precise enough for your current analysis; this would be the place to improve the logic (in particular, line 55 looks most peculiar).

**Comment by jurgenvinju** [comment]
I'll try and make an example, either from memory or using a typical C++ example like the snakes and ladders game.

**Comment by rodinaarssen** [comment]
Just something small and constructed would suffice, I suppose

**Comment by jurgenvinju** [comment]
solved this by fixing the code that @rodinaarssen pointed to, and also added tests
