### ISSUE TITLE
Parsing problems with enums, lambdas and nothrows.

### ISSUE THREAD

**Issue by NemuruYama** [usethesource/clair#68]
For a project I have to parse Cpp files in a bigger project, but there seem to be some problems.
These are just the ones I have found for now, there may be more that I haven't found in my list of errors yet.
The code has been modified as it is run on code I am not allowed to share for my research project.
If I removed too much, tell me and I will see how much I can add back.

I use Rascal 0.33.1 and ClaiR 0.9.2.

### Public Enum Class
Input:
```cpp
public enum class CLASS_NAME {
  ENUM_VALUE_1,
};
```
Result:
translationUnit(
  [problemDeclaration(src=|cwd:///test.cpp|(0,57))],
  src=|cwd:///test.cpp|(0,59),
  decl=|cpp+translationUnit:///test.cpp|)

### Lambda Functions
Input:
```cpp
auto lambdaFunc = []
{
	// Any code here
};
```

Output:
missingdeclarator after the [] with a length of 0. 

### Another lambda
Input:
```cpp
int ReceiveTest();
std::thread receiver([&] {receiveError = ReceiveTest(); });
```
 Result:
Missing declarator after the [&] of length 0.

### Nothrow
```cpp
// ObjectDictionary() is a class constructor.
#define NOTHROW (std::nothrow)
x = new NOTHROW ObjectDictionary();
```
Result: Statement problem on the entire line of `x = ...`

**Comment by jurgenvinju** [comment]
Thanks @NemuruYama for your report.

**Comment by jurgenvinju** [comment]
It would be helpful to know which compiler this project is using and which compiler settings. These issues look like C++ language compatibility issues. We can find out if there is an option to set on the underlying CDT parser we are using, or if something else is going on. 

Please tell us: 

* C++ compatibility version (this is a compiler flag)
* Compiler version (just to be sure)

It is also possible that in the same project different options are being used. Usually they can be found in visual studio project files or in `Makefile`s. If it's a GNU project then the configuration can be found in autoconf or automake files. Running `make` is also an option. You'll see all the options to the compiler printed in the log.

Thanks!

**Comment by rodinaarssen** [comment]
**Public enum class**: this seems to be a [Microsoft-specific extension to the standard](https://learn.microsoft.com/en-us/cpp/extensions/enum-class-cpp-component-extensions?view=msvc-170), which is not supported by the underlying version of CDT.

**Lambda functions**: this is expected behavior: indeed, there is no declarator in that lambda definition (in `[](int a) { return a; }`, the `(int a)` part is the declarator).

**Another lambda**: the same holds here.

**Nothrow**: I cannot reproduce the parse error, this parses just fine for me. Could you perhaps provide some more context?

**Comment by NemuruYama** [comment]
Thank you for checking.

**NOTHROW:** Maybe a better example is this:
```cpp
#if defined(_MSC_VER)
#define NOTHROW __nothrow
#endif

#include <cstdint>

int main()
{
  uint8_t* buff = new NOTHROW uint8_t[128];
}
```

```
Declaration: translationUnit(
  [functionDefinition(
      declSpecifier(
        [],
        integer(src=|cwd:///test.cpp|(140,3)),
        src=|cwd:///test.cpp|(140,3)),
      functionDeclarator(
        [],
        [],
        name(
          "main",
          src=|cwd:///test.cpp|(144,4)),
        [],
        [],
        src=|cwd:///test.cpp|(144,6),
        decl=|cpp+function:///main()|),
      [],
      compoundStatement(
        [problem(
            "uint8_t* buff = new NOTHROW uint8_t[5111808u];",
            src=|cwd:///test.cpp|(157,46),
            isMacroExpansion=true)],
        src=|cwd:///test.cpp|(152,54),
        isMacroExpansion=true),
      src=|cwd:///test.cpp|(140,66),
      isMacroExpansion=true)],
  src=|cwd:///test.cpp|(0,206),
  decl=|cpp+translationUnit:///test.cpp|,
  isMacroExpansion=true)
```

**Public enum class:** This is kind of a problem, but it appears I need to work around this, thank you for explaining.

**Lambda:** I figured there should not be a problem created there if it is expected behaviour.

**Comment by rodinaarssen** [comment]
Your latest code fragment would fail in case the preprocessor cannot find a definition for `_MSC_VER`. However, I don't think `__nothrow` is part of the C++ standard either.

**Comment by NemuruYama** [comment]
You are indeed correct, __nothrow (which is based on __declspec) is a Microsoft extension as well, so it appears there is no problem as this is an incompatibility between the Eclipse CDT and the Microsoft compiler. See [this](https://stackoverflow.com/questions/2284610/what-is-declspec-and-when-do-i-need-to-use-it) link.

I would imagine that there is not an easy way to fix this?

**Comment by NemuruYama** [comment]
Thank you, I will see if I can use that.
Closing the issue.

**Comment by jurgenvinju** [comment]
Thanks Lucas; if anything pops up , please don't hesitate to create another issue.
