### ISSUE TITLE
Names too unique

### ISSUE THREAD

**Issue by linuswagner** [usethesource/clair#72]
A function declared as `const char* glfwGetGamepadName(int jid);` gets the following entries in the declarations of the M3 model:
```
{  
  <|cpp+function:///abs/path/proj_1/some_file.ii/glfwGetGamepadName(int)|,|file:///abs/path/proj_1/some_file.ii|(10988015,29)>,  
  <|cpp+function:///abs/path/proj_2/some_file_1.ii/glfwGetGamepadName(int)|,|file:///abs/path/proj_2/some_file_1.ii|(10925299,29)>,  
  <|cpp+function:///abs/path/proj_2/some_file_2.ii/glfwGetGamepadName(int)|,|file:///abs/path/proj_2/some_file_2.ii|(10925299,29)>,  
  <|cpp+function:///abs/path/proj_2/some_file_3.ii/glfwGetGamepadName(int)|,|file:///abs/path/proj_2/some_file_3.ii|(10925299,29)>,  
  <|cpp+function:///abs/path/proj_3/some_file.ii/glfwGetGamepadName(int)|,|file:///abs/path/proj_3/some_file.ii|(11038201,29)>  
}
```
Look at the physical location of the element in `proj_2` (the 3 files in the middle). It is always at the same position, because the include that gets resolved from the preprocessor is identical.

Structure:
- There are three projects (`proj_1`, `proj_2`, `proj_3`) which have files that start with a precompiled header followed by a bunch of cpp files.
- `proj_2` has this structure (with the same precompiled header) three times.
- Each of the files gets a single M3, which is then incrementally merged together resulting in the tuples above.

The callgraph is empty, because for some reason, the function is unused.

**Comment by jurgenvinju** [comment]
* There is a design error in the naming of functions here. The compilation unit prefix makes all the function names different, while they are the same
* When this name is used by the resolution of the callee, then there will be no function definition to match and the call graph is empty

**Comment by jurgenvinju** [comment]
It's one of those "how could this have ever worked" moments, that are all too familiar :-)

**Comment by jurgenvinju** [comment]
* have to figure out how to weave the semantics of the `static` modifier into this. `static` functions are local to their compilation unit only.

**Comment by jurgenvinju** [comment]
I think this is where I broke the system: 51e640fc12592d50bdf6854cf070663d24546d26

**Comment by jurgenvinju** [comment]
* The containment relation needs a specific name for the compilationUnit, in that way we can see which function is defined where.
* But when something is owned by a compilation unit, it's unique name should not have that specific name as the prefix of the path. Then the prefix should be empty.

**Comment by jurgenvinju** [comment]
@ruichen-ing did this trouble you too and what did you do to work around? Or did we work with a version before I introduced this bug?
