### ISSUE TITLE
parseFiles contains debug prints

### ISSUE THREAD

**Issue by linuswagner** [usethesource/clair#77]
the following methods contains 3 prints
https://github.com/usethesource/clair/blob/bd0b80dd038563ec44d9dd633d77daeab6acbe5f/src/lang/cpp/internal/Parser.java#L290

are these on purpose?
```
out("Beginning at " + begin.toString());
```

```
out("CDT took " + (Duration.between(begin, between).toMillis() * 1.0d) / 1000 + "seconds");
```

```
out("Marshalling took " + (Duration.between(between, done).toMillis() * 1.0d) / 1000
					+ "seconds");
```

**Comment by jurgenvinju** [comment]
It's ok to remove them. Thanks @linuswagner
